### ISSUE TITLE
Is there a copyright stated? 

### ISSUE THREAD

**Issue by hschellman** [knoepfel/meld#1]

**Comment by knoepfel** [comment]
Good catch, @hschellman. I believe it should be Fermilab.  I'll get that sorted out.

**Comment by hschellman** [comment]
Check out any of our code.   You do have the nice license.

On Jul 3, 2023, at 12:12 PM, Kyle Knoepfel ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Good catch, @hschellman<https://github.com/hschellman>. I believe it should be Fermilab. I'll get that sorted out.

**Comment by knoepfel** [comment]
@hschellman, I've added a NOTICE file per Fermilab guidance:

https://github.com/knoepfel/meld/blob/main/NOTICE
